# This clippys, docs, tests, builds.

name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Awarnings

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~\.cargo
          target
        key: windows
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Clippy
      run: cargo clippy --all-features
    - name: Doc
      run: cargo doc --workspace --no-deps --all-features
    - name: Test
      run: cargo test --all-features
    - name: Build
      run: cargo build --all-features
